#!/bin/bash

if [ $# -ne 2 ] ; then
  echo input and output filenames are expected
  exit 1
fi

in="$1"
out="$2"

echo "<html><body><pre>" > "$out"
sed -E 's|\&|\&amp\;|g; s|<|\&lt\;|g; s|>|\&gt\;|g; s|#include "([a-zA-Z0-9_-]+\.h)"|#incude "<a target='"'"'\1'"'"' href='"'"'\1.html'"'"'>\1</a>"|g; s|//#target ([^0]+)$|<a name='"'"'\1'"'"'></a>|g' "$1" >> "$out"
echo "</pre></body></html>" >> "$out"

