#!/bin/bash

hostname=`hostname`
DIR=`dirname "$(realpath $0)"`
os=`${DIR}/../getos`
bindir="${DIR}/../binaries/${os}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${bindir}"
chmod +x "${bindir}/apdcam-daq.exe"
${bindir}/apdcam-daq.exe "$@"




