#!/bin/bash

hostname=`hostname`
DIR=`dirname "$(realpath $0)"`
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DIR}/..:${DIR}"
if [ "$hostname" = "SPI-GAP2" ] ; then
    ${DIR}/../ubuntu-20.04/apdcam-daq.exe "$@"
else    
    ${DIR}/apdcam-daq.exe "$@"
fi




